### ISSUE TITLE
Płytka prototypowa

### ISSUE THREAD

**Issue by rinpg** [rinpg/Zegar#1]

**Comment by bstyczen96** [comment]
Ogarnięcie aby móc ułożyć proste obwody elektroniczne na płytce, 2 godziny

**Comment by TheKrzysiek108INPG** [comment]
Zapoznanie się ze sposobami układania podstawowych obwodów elektrycznych. (2h)

**Comment by michallozinski** [comment]
Zdobycie wiedzy na temat podstawowych obwodów elektrycznych na płytkach i programatorów USBasp (1,5h)

**Comment by rinpg** [comment]
Ogarniecie płytki prototypowej, przewodów, oraz podstawowych elementów elektronicznych 2h

**Comment by rinpg** [comment]
przyswojone przez wszystkich zamykam.
