### ISSUE TITLE
Atmega8

### ISSUE THREAD

**Issue by rinpg** [rinpg/Zegar#2]

**Comment by bstyczen96** [comment]
Przyswojenie podstawowych pojęć na temat mikrokontrolerów, pozwalających na napisanie prostego programu do migania diody w celu utrwalenia zdobytej wiedzy. Commit: Zegar/test_LED_blink

**Comment by TheKrzysiek108INPG** [comment]
Zaznajomienie się z teorią dotyczącą mikrokontrolerów, przetestowanie prostego programu w symulatorze AVR. Commit: Zegar/DATA/Symylator AVR.txt  (1,5h)

**Comment by michallozinski** [comment]
Ogarnięcie teorii mikrokontrolerów, praca w symulatorze AVR, teoria związana z programatorem USBasp (2h)

**Comment by rinpg** [comment]
przyswojone przez wszystkich zamykam.
